name: absensi_jidoka
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  firebase_storage: ^11.0.14
  cloud_firestore: ^4.4.3
  image_picker: ^0.8.6+3
  intl: ^0.17.0
  syncfusion_flutter_datepicker: ^20.4.51
  
  geocoding: ^2.0.5
  lottie: ^2.2.0
  google_maps_flutter: ^2.2.4
  geolocator: ^9.0.2
  get_storage: ^2.0.3
  connectivity_checker: ^1.1.0
  flutter_offline: ^2.1.0
  convex_bottom_bar: ^3.2.0
  trust_location: ^2.0.13
  sqflite: ^2.2.5
  ntp: ^2.0.0


dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/login.json
    - assets/jidoka.png
    - assets/jidoka_logo.png
    - assets/cowok.jpg
  uses-material-design: true


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/jidoka_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


