// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4tPgFzZ8Qfztzwo6zsNLkOKXXK1JQl0Q',
    appId: '1:336220922054:web:2341ade45a1be2d30bf7c7',
    messagingSenderId: '336220922054',
    projectId: 'absensi-jidoka',
    authDomain: 'absensi-jidoka.firebaseapp.com',
    storageBucket: 'absensi-jidoka.appspot.com',
    measurementId: 'G-PRZGRHESBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAg0DMWnHm0rEuPrHsHilplWY7NFCWjEw',
    appId: '1:336220922054:android:84c1ebb9603e5fd80bf7c7',
    messagingSenderId: '336220922054',
    projectId: 'absensi-jidoka',
    storageBucket: 'absensi-jidoka.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmvfqMXaBx05WF8Vqe9LrBsqQGy402VYI',
    appId: '1:336220922054:ios:76cfb84b0e11a5960bf7c7',
    messagingSenderId: '336220922054',
    projectId: 'absensi-jidoka',
    storageBucket: 'absensi-jidoka.appspot.com',
    iosClientId: '336220922054-j2lp5k2dfg90eoj21mp9ifsdlbrar4dq.apps.googleusercontent.com',
    iosBundleId: 'com.example.absensiJidoka',
  );
}
